#! /usr/bin/env bash

# TODO: make username and password optional flags
username='ms'
# read -p "Enter username : " username
# read -s -p "Enter password : " password

if [ "$EUID" -ne 0 ]
then
  echo ==================================
  echo Please be root
  echo ==================================
  exit 2
fi

# TODO: move user spesifics to ansible
echo ==================================
echo "Add user $username"
echo ==================================

egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
	echo "$username exists!"
else
	#pass=$(perl -e 'print crypt($ARGV[0], "XWDJ$fEdn47qKyZ")' $password)
  pass=XW5JBvHWXvnwM
	useradd -m -p "$pass" "$username"
	[ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
fi

echo ==================================
echo Installing sudo and adding user
echo ==================================
apt install sudo
adduser $username sudo

echo ==================================
echo Installing packages
echo ==================================
apt update
apt upgrade -y

apt install python3 -y
apt install python3-pip -y
apt install git -y
apt install ansible -y

echo ==================================
echo Adding ssh keys
echo ==================================
wget -qO /home/$username/.ssh/authorized_keys https://github.com/stromdahl.keys

echo ==================================
echo All done, have fun!
echo ==================================
