#! /usr/bin/env bash

if [ "$EUID" -ne 0 ]
then
  echo ==================================
  echo Please be root
  echo ==================================
  exit 1
fi

echo ==================================
echo Update and Upgrade
echo ==================================
apt update
apt upgrade -y


NAME='ms'
echo ==================================
echo "Add user $NAME"
useradd $NAME || echo "User '$NAME' exists"
echo ==================================
mkdir -p /home/$NAME

echo ==================================
echo Installing sudo and adding user
echo ==================================
apt install sudo
adduser $NAME sudo

echo ==================================
echo Installing python3 and pip
echo ==================================
apt install python3 -y
apt install python3-pip -y

NAME=$(id -nu 1000)
sudo -i -u $NAME bash << EOF
echo ==================================
echo Installing ansible as user \'$NAME\'
echo ==================================
python3 -m pip install --user ansible
ansible --version
EOF

echo ==================================
echo All done, have fun!
echo ==================================
