---
- name: Install rustup
  shell:
    warn: False
    cmd: curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
    creates: ~/.cargo/bin/rustup

- name: Check for updates with rustup
  register: rustup_check
  changed_when: False
  shell: ~/.cargo/bin/rustup check

- name: Run rustup update
  when: '"Update available" in rustup_check.stdout'
  shell: ~/.cargo/bin/rustup update

- name: Download rust-analyzer
  register: rust_analyzer
  get_url:
    url: https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz
    dest: ~/.cache/rust-analyzer.gz

- name: Unpack and replace rust-analyzer
  when: rust_analyzer.changed
  shell: rm ~/bin/rust-analyzer && gzip -dc ~/.cache/rust-analyzer.gz > ~/bin/rust-analyzer && chmod +x ~/bin/rust-analyzer
  args:
    warn: False
