---
- name: Install workstation tools
  become: yes
  apt:
    state: present
    name:
      - ansible
      - fonts-hack
      - fonts-powerline
      - gnome-disk-utility
      - i3
      - lightdm
      - neovim
      - scrot
      - xclip
      - xfce-terminal

- name: Create directories
  file: 
    path: "{{ item }}"
    state: directory
  loop:
    - downloads

- name: Ensure /etc/X11/xorg.conf.d exists
  become: yes
  file:
    path: /etc/X11/xorg.conf.d
    state: directory


