---
- name: Stat dotfile
  stat:
    path: "{{ansible_user_dir}}/{{dotfileInfo.install_path}}"
  register: dotfile_stat

- name: Delete original dotfile
  when: dotfile_stat.stat.isreg is defined and dotfile_stat.stat.isreg == True
  file:
    path: "{{ansible_user_dir}}/{{dotfileInfo.install_path}}"
    state: absent

- name: Symlink dotfile
  file:
    src: "{{configs_dir}}/{{dotfileInfo.repo_path}}"
    dest: "{{ansible_user_dir}}/{{dotfileInfo.install_path}}"
    state: link
